---
name: Monitor verified batches

# Reusable workflow
on:
  workflow_call:

env:
  # The minimum number of batches to be verified
  VERIFIED_BATCHES_TARGET: 30
  # The script timeout (in seconds)
  TIMEOUT: 600 # 10 minutes

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check that batches are being verified
        working-directory: scripts
        run: ./batch_verification_monitor.sh ${{ env.VERIFIED_BATCHES_TARGET }} ${{ env.TIMEOUT }}
